# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - 3.4
  - 2.7

env:
  matrix:
  - DJANGO='django16' CMS='cms30'
  - DJANGO='django16' CMS='cms31'
  - DJANGO='django17' CMS='cms30'
  - DJANGO='django17' CMS='cms31'
  - DJANGO='django17' CMS='cms32'
  - DJANGO='django18' CMS='cms31'
  - DJANGO='django18' CMS='cms32'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox>=1.8 coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e"$PYVER-$DJANGO-$CMS"

after_success: coveralls
