# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - 3.3
  - 3.4
  - 2.7
  - 2.6

env:
  matrix:
  - DJANGO='django14' CMS='cms30'
  - DJANGO='django15' CMS='cms30'
  - DJANGO='django16' CMS='cms30'
  - DJANGO='django16' CMS='cms31'
  - DJANGO='django17' CMS='cms30'
  - DJANGO='django17' CMS='cms31'
  - DJANGO='django18' CMS='cms31'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox>=1.8 coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then export PYVER=py26; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then export PYVER=py33; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e"$PYVER-$DJANGO-$CMS"

after_success: coveralls

matrix:
  exclude:
    - python: 2.6
      env: DJANGO='django17' CMS='cms30'
    - python: 2.6
      env: DJANGO='django17' CMS='cms31'
    - python: 2.6
      env: DJANGO='django18' CMS='cms30'
    - python: 2.6
      env: DJANGO='django18' CMS='cms31'
    - python: 3.3
      env: DJANGO='django14' CMS='cms30'
    - python: 3.4
      env: DJANGO='django14' CMS='cms30'

  allow_failures:
    - python: 2.7
      env: DJANGO='django18' CMS='cms31'
    - python: 3.3
      env: DJANGO='django18' CMS='cms31'
    - python: 3.4
      env: DJANGO='django18' CMS='cms31'